### ISSUE TITLE
Question about the Infrastructure layer

### ISSUE THREAD

**Issue by WarBorg** [martinstm/onion-architecture#1]
hello,

I have read your article on Medium and found thins repository linked there, and I have a question: why does your Infrastructure layer has a direct access (dependencies) to your Domain and Domain.Service layers ? I think you mentioned in your article that the door to those layers should be the Application layer ? did I miss something ?

**Comment by martinstm** [comment]
Hi,

Thanks for your comment!
Your question is really relevant. The Onion Architecture avoids that a central layer knows about an outer layer from it. The outer ring, which contains infrastructure, contains all things that can change often. Since you have your repository interfaces in the Domain Services ring, you just are coupled to that central layer in your implementation. In that case, you could have multiple implementations of your repository interface. For example to use with an in-memory database, a SQL database, a MongoDB database, etc. 
You must have an injection mechanism to get the implementation, in runtime, that will be used when your application is running.

I hope this answers your question! If not, please tell me.

Regards.
